### ISSUE TITLE
Original image height is too small! (ChunkyPNG::OutOfBounds)

### ISSUE THREAD

**Issue by anilreddy** [ansoni/watir-extensions-element-screenshot#1]
I am getting the below error when trying to capture screenshots of elements

C:/Ruby200/lib/ruby/gems/2.0.0/gems/chunky_png-1.3.1/lib/chunky_png/canvas/opera
tions.rb:175:in `crop!': Original image height is too small! (ChunkyPNG::OutOfBo
unds)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watir-extensions-element-screen
shot-0.0.2/lib/watir/extensions/element/screenshot.rb:11:in`screenshot'
        from angular_test.rb:15:in `<main>'

**Comment by malditojavi** [comment]
In my case, same issue, but `div` had neither specific width nor height. Specifying a full-size resolution when opening the Browser seems to do the trick to grab the screenshot:

    browser = Watir::Browser.new :chrome
    browser.window.resize_to(1900, 1080)
