### ISSUE TITLE
Selenium::WebDriver::Error::WebDriverError: unexpected response

### ISSUE THREAD

**Issue by f4th4n** [ansoni/watir-extensions-element-screenshot#6]
```
irb(main):010:0> browser.div(:id => "hplogo").screenshot("logo_google.png")
Selenium::WebDriver::Error::WebDriverError: unexpected response, code=404, content-type="text/plain"
Error - Unable to load Atom 'find_element' from file ':/ghostdriver/./third_party/webdriver-atoms/find_element.js'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:85:in `create_response'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:627:in `execute'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:596:in `find_element_by'
    from /var/lib/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/search_context.rb:61:in `find_element'
    from /var/lib/gems/2.3.0/gems/watir-webdriver-0.9.3/lib/watir-webdriver/locators/element/locator.rb:75:in `by_id'
    from /var/lib/gems/2.3.0/gems/watir-webdriver-0.9.3/lib/watir-webdriver/locators/element/locator.rb:39:in `locate'
    from /var/lib/gems/2.3.0/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:551:in `locate'
    from /var/lib/gems/2.3.0/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:505:in `assert_exists'
    from /var/lib/gems/2.3.0/gems/watir-webdriver-0.9.3/lib/watir-webdriver/elements/element.rb:391:in `wd'
    from /var/lib/gems/2.3.0/gems/watir-extensions-element-screenshot-0.0.3/lib/watir/extensions/element/screenshot.rb:11:in `screenshot'
    from (irb):10
    from /usr/bin/irb:11:in `<main>'
```

OS Ubuntu 16, Browser PhantomJS

**Comment by PatchRanger** [comment]
Looks like Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/phantomjs/+bug/1578444 .
